DS-1692 Use Spark-CSV in Read/Write DataFrame
  The following changes come within this commit:

  * ReadDataFrame no longer supports line separator parameter (API change!)
    - instead, CR/CRLF are detected automatically
  * If the user specifies that the file contains a header row,
    column names have to be unique. If they aren't,
    InvalidArgumentException is thrown.
  * Treating quote characters is closer to RFC 4180:
    - quotes appearing inside a quoted field have to be escaped
      with another qoute:
        aaa,"He said ""Hi!""",ccc
    - quotes appearing inside un-quoted field are treated as any other character
      (contrary to what the RFC says) unless the field begins with a quote.
        aaa,He said "Hi!",ccc
        IOException: aaa,"Hi!" - he said,ccc

  * If the first value in a row is empty, WriteDataFrame writes is as ""
  * Each line is trimmed before writing, which results in badly
    formatted CSV when tab or space are used as column separator and one
    or more fields at the end of the row are empty
  * Strings contining column separators other than ',' are quoted properly

  Also, noted for completeness:
  * Field separator inside a quoted field does not denote a beginning
    of a new field
  * Quoted numbers are no longer treated as strings
  * String fields are no longer trimmed
  * Column names are trimmed

Change-Id: I7a0a46275db6d849eed9bc77da35414493606937